stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker build -t qiushaocloud/site-counter:latest .
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/site-counter:latest
  tags:
    - qiushaocloud-runner

build-tags:
  stage: build
  only:
    - tags
  script:
    - docker build -t qiushaocloud/site-counter:$CI_COMMIT_REF_NAME .
    - docker tag qiushaocloud/site-counter:$CI_COMMIT_REF_NAME qiushaocloud/site-counter:latest
    # - docker build -t qiushaocloud/site-counter:latest .
  tags:
    - qiushaocloud-runner

deploy-tags:
  stage: deploy
  only:
    - tags
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/site-counter:$CI_COMMIT_REF_NAME
    - docker push qiushaocloud/site-counter:latest
  tags:
    - qiushaocloud-runner
